[package]
name = "reflow"
version = "0.1.0"
authors = ["mut"]

[dependencies]
bytes = "0.4"
env_logger = "0.5.*"
failure = "0.1.1"
futures = "0.1.20"
log = "^0.4"
tokio = "0.1.6"
radix_trie = "0.1.*"
structopt = "^0"
treebitmap = { path="../treebitmap" }
trust-dns-server = "0.14.0"
trust-dns = "0.14.0"
trust-dns-proto = "0.4.0"
toml = "0.4.2"
serde_derive = "1.0.21"
serde="1.0"
