[package]
name = "reflow"
version = "0.1.0"
authors = ["mut"]

[dependencies]
byteorder = "1.2.3"
bytes = "^0.4"
env_logger = "0.5.*"
failure = "0.1.1"
futures = "0.1.20"
futures-cpupool = "^0"
httparse = "^1.0"
log = "^0.4"
tokio = "0.1.6"
tokio-io = "^0.1"
radix_trie = "0.1.*"
socks = "^0.3"
structopt = "^0"
treebitmap = "0.3.1"
trust-dns = "0.14.0"
trust-dns-resolver = "0.9.0"
toml = "0.4.2"
serde_derive = "1.0.21"
serde="1.0"
